CREATE TABLE MEMBER1(
	ID VARCHAR(20) PRIMARY KEY,
	PASSWORD VARCHAR(30) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	AGE NUMBER,
	ADDRESS VARCHAR(40),
	EMAIL VARCHAR(40),
	GENDER VARCHAR(10)
	);
	
INSERT INTO MEMBER1 VALUES ('admin','1111','관리자',12,'인천 미추홀구','u@naver.com','여자');
COMMIT
SELECT * FROM MEMBER1 WHERE id='admin' and password='1111';