CREATE TABLE BOARD(
	BOARD_NUM NUMBER,
	BOARD_NAME VARCHAR(20) NOT NULL,
	BOARD_PASS VARCHAR(15) NOT NULL,
	BOARD_SUBJECT VARCHAR(50) NOT NULL,
	BOARD_CONTENT VARCHAR(2000) NOT NULL,
	BOARD_FILE VARCHAR(50),
	BOARD_RE_REF NUMBER NOT NULL,
	BOARD_RE_LEV NUMBER NOT NULL,
	BOARD_RE_SEQ NUMBER NOT NULL,
	BOARD_READCOUNT NUMBER DEFAULT 0,
	BOARD_DATE DATE,
	PRIMARY KEY(BOARD_NUM));
	
	CREATE SEQUENCE SEQ START WITH 1 INCREMENT BY 1;
	DROP SEQUENCE SEQ;
	
SELECT * FROM BOARD;
DROP TABLE BOARD;

UPDATE BOARD SET BOARD_READCOUNT=2 WHERE BOARD_NUM=1;
UPDATE BOARD SET BOARD_CONTENT ='AA',BOARD_SUBJECT='AA' WHERE BOARD_NUM=1;
DELETE FROM BOARD WHERE BOARD_NUM='1';